---
dotfiles:
  repo: https://github.com/wittyjudge/dotfiles.git
  dest: "{{ ansible_user_dir }}/dotfiles"

tmux_plugin_manager: 
  repo: "https://github.com/tmux-plugins/tpm"
  dest: "{{ ansible_user_dir }}/.config/tmux/plugins/tmp"
