#!/usr/bin/env bash

set -e

echo "[i] Ask for sudo password"
sudo -v

case "$(uname -s)" in
  Linux)
    [ ! -f /etc/os-release ] && echo '[!] Unsupported Linux Distribution' && exit 1
    [ ! -x "$(command -v ansible)" ] && ansible_not_installed=true

    . /etc/os-release

    case "$ID" in
      arch)
        if  [ $ansible_not_installed ]; then
          echo "[i] Install Ansible"

          sudo pacman -S --noconfirm ansible
          ansible-galaxy install -r requirements.yaml
        fi
        ;;
      *)
        echo "[!] Unsupported Linux Distribution: $ID"
        exit 1
        ;;
    esac
    ;;
esac

echo "[i] Run Playbook"
ansible-playbook bootstrap.yml --ask-become-pass --tags all

echo "[i] From now on you can use $ dotfiles to manage your dotfiles"
echo "[i] Done."
