---
- become: true
  tags: archlinux_packages
  block:
    - name: Update/Upgrade pacman (pacman -Syu)
      community.general.pacman:
        update_cache: true
        upgrade: true

    - name: Refresh Arch keyrings.
      community.general.pacman:
        name: archlinux-keyring
        state: latest

    - name: Install important packages
      community.general.pacman:
        name:
          - curl
          - git
          - base-devel
        state: present

    - name: Install reflector
      community.general.pacman:
        name: reflector
        state: present
      notify:
        - Start reflector service

    - name: Install Network Manager
      community.general.pacman:
        name: networkmanager
        state: present
      notify:
        - Start NetworkManager service

    - name: Install packages.csv file
      ansible.builtin.get_url:
        url: "{{ packages_csv_src }}"
        dest: "{{ packages_csv_dest }}"
        force: true

    - name: Read packages.csv file
      community.general.read_csv:
        path: "{{ packages_csv_dest }}"
      register: packages

    - name: Set facts with the packages list
      ansible.builtin.set_fact:
        pacman_packages: "{{ packages.list | selectattr('SKIP', 'equalto', '') | selectattr('TAG', 'equalto', '') | map(attribute='PROGRAM') | list }}"
        aur_packages: "{{ packages.list | selectattr('SKIP', 'equalto', '') | selectattr('TAG', 'equalto', 'AUR') | map(attribute='PROGRAM') | list }}"

    - name: Install pacman packages
      community.general.pacman:
        name: "{{ item }}"
        state: present
      ignore_errors: true
      loop: "{{ pacman_packages }}"

    - name: Install AUR packages
      ansible.builtin.import_role:
        name: makepkg
      vars:
      # Add yay-bin to the aur packages list
        makepkg_packages: "{{ ['yay-bin'] + aur_packages }}"
