---
- name: Clone dotfiles repository
  git:
    repo: "{{ dotfiles.repo }}"
    dest: "{{ dotfiles.dest }}"
    update: false
  become: true
  become_user: "{{ ansible_user_id }}"

- name: Chmod dotfiles/.local/bin folder
  file:
    path: "{{ dotfiles_git_dest }}/.local/bin"
    state: directory
    mode: 0755
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    recurse: true
  become: true

- name: Run a setup script
  command: bash setup
  args:
    chdir: "{{ dotfiles_git_dest }}"
  become: true
  become_user: "{{ ansible_user_id }}"

- name: Clone tmux plugin manager repository
  git:
    repo: "{{ tmux_plugin_manager.repo }}"
    dest: "{{ tmux_plugin_manager.dest }}"
    update: false
  become: true
  become_user: "{{ ansible_user_id }}"
