---
- name: Clone dotfiles repository
  git:
    repo: "{{ dotfiles_git_src }}"
    dest: "{{ dotfiles_git_dest }}"
    update: no
  become: yes

- name: Chmod dotfiles/.local/bin folder
  file:
    path: "{{ dotfiles_git_dest }}/.local/bin"
    state: directory
    mode: 0755
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    recurse: yes
  become: yes

- name: Run a setup script
  command: bash setup --noconfirm
  args:
    chdir: "{{ dotfiles_git_dest }}"
  become: yes
  become_user: "{{ ansible_user_id }}"
