---
- name: Configure pacman
  lineinfile:
    path: ./test/pacman.conf
    # path: /etc/pacman.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backrefs: "{{ item.backrefs }}"
    state: present
  loop:
    - { line: "Color", regexp: "^#?Color$", backrefs: yes }
    - { line: "ILoveCandy", regexp: "^#?ILoveCandy$", backrefs: yes }
    - { line: "ParallelDownloads = 5", regexp: "#ParallelDownloads", backrefs: yes }

- name: Enable pacman repositories
  ini_file:
    path: ./test/pacman.conf
    # path: /etc/pacman.conf
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value | default(omit) }}"
    state: present
  loop:
    - { section: "multilib", option: "Include", value: "/etc/pacman.d/mirrorlist" }
  become: yes
