---
- name: Create folders
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ ansible_user_dir }}/projects/golang/src"
    - "{{ ansible_user_dir }}/Pictures/screenshots"
  become: true
  become_user: "{{ ansible_user_id }}"
