---
- name: Setup user related settings
  include_tasks: user.yml
  when: create_new_user != False

- include_tasks: folders.yml

- name: Arch Linux specific tasks
  include_tasks: archlinux.yml
  when: ansible_os_family == "Archlinux"
