---
- name: Get stats of the sudoers.pacnew
  stat:
    path: /etc/sudoers.pacnew
  register: sudoers_pacnew_file

- name: Copy sudoers.pacnew into sudoers
  copy:
    src: /etc/sudoers.pacnew
    dest: /etc/sudoers
    validate: visudo -cf %s
  become: yes
  when: sudoers_pacnew_file.stat.exists

- name: Make sure we have a 'wheel,docker' groups
  group:
    name: "{{ item }}"
    state: present
  with_items: 
    - wheel
    - docker
  become: yes

- name: Allow 'wheel' group to have passwordless
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: "^%wheel"
    line: "%wheel ALL=(ALL:ALL) NOPASSWD: ALL"
    validate: visudo -cf %s
  become: yes

- name: New user
  when: create_new_user != False | default(False)
  block:
    - name: Create '{{ username }}' user
      user:
        name: "{{ username }}"
        password: "{{ user_password | string | password_hash('sha512') }}"
        groups: 
          - wheel 
          - users 
          - input 
          - network
          - docker
        append: yes
        state: present
      become: yes
      register: new_user

    - name: Rewrite default ansible facts with a newly created user
      set_fact:
        ansible_user_id: "{{ new_user.name }}"
        ansible_user_dir: "{{ new_user.home }}"
