---
- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present
  become: yes

- name: Get stats of the sudoers.pacnew
  stat:
    path: ./test/sudoers.pacnew
  register: sudoers_pacnew_file

- name: Copy sudoers.pacnew into sudoers
  copy:
    src: ./test/sudoers.pacnew
    # src: /etc/sudoers.pacnew
    dest: ./test/sudoers
    # dest: /etc/sudoers
    validate: visudo -cf %s
  become: yes
  when: sudoers_pacnew_file.stat.exists

- name: Allow wheel group to have passwordless
  lineinfile:
    path: ./test/sudoers
    # path: /etc/sudoers
    state: present
    regexp: "^%wheel"
    line: "%wheel ALL=(ALL:ALL) NOPASSWD: ALL"
    validate: visudo -cf %s
  become: yes

- name: Create {{ username }} user
  user:
    name: "{{ username }}"
    password: "{{ user_password | string | password_hash('sha512') }}"
    groups: wheel,users,input,docker
    append: yes
    state: present
  become: yes
  register: new_user

- name: Rewrite default ansible facts with a newly created user
  set_fact:
    ansible_user_id: "{{ new_user.name }}"
    ansible_user_dir: "/home/{{ new_user.home }}"
    XDG_DATA_HOME: "{{ ansible_user_dir }}/.local/share"

# - name: Chmod the user home directory
#   file:
#     path: "{{ ansible_user_dir }}"
#     state: directory
#     mode: 0755
#     owner: "{{ username }}"
#     group: "{{ username }}"
#     recurse: yes
#   become: yes
