- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present
  become: yes

- name: Create User
  user:
    name: "{{ username }}"
    password: "{{ user_password | string | password_hash('sha512') }}"
    groups: wheel,users,input,docker
    append: yes
    state: present
  become: yes
  register: new_user

- name: Set a fact with a newly created user
  set_fact:
    user_home_path: "{{ new_user.home }}"

- name: Get stats of the sudoers.pacnew
  stat:
    path: ./test/sudoers.pacnew
  register: sudoers_pacnew_file

- name: Copy sudoers.pacnew into sudoers
  copy:
    src: ./test/sudoers.pacnew
    dest: ./test/sudoers
    validate: visudo -cf %s
  become: yes
  when: sudoers_pacnew_file.stat.exists

- name: Allow wheel group to have passwordless
  lineinfile:
    path: ./test/sudoers
    # path: /etc/sudoers
    state: present
    regexp: "^%wheel"
    line: "%wheel ALL=(ALL:ALL) NOPASSWD: ALL"
    validate: visudo -cf %s
  become: yes
