---
- name: Git clone asdf
  git:
    repo: "{{ asdf_git_src }}"
    dest: "{{ asdf_dir }}"
  become: yes
  become_user: "{{ ansible_user_id }}"

- name: Install asdf plugins
  shell: >-
    source {{ asdf_dir }}/asdf.sh &&
    asdf plugin add {{ item.name }} {{ item.repository | default() }}
  args:
    creates: "{{ asdf_dir }}/plugins/{{ item.name }}"
  with_items: "{{ asdf_plugins }}"
  ignore_errors: yes

- name: Install asdf packages
  shell: >-
    source {{ asdf_dir }}/asdf.sh &&
    asdf install {{ item.0.name }} {{ item.1 }}
  args:
    creates: "{{ asdf_dir }}/installs/{{ item.0.name }}/{{ item.1 }}"
  with_subelements:
    - "{{ asdf_plugins }}"
    - versions
    - flags:
      skip_missing: yes

- name: Get current asdf package versions
  shell: >-
    set -o pipefail &&
    source {{ asdf_dir }}/asdf.sh &&
    asdf current {{ item.name }} |
    grep -o '{{ item.global | default(item.versions[0]) }}'
  register: asdf_plugins_versions
  with_items: "{{ asdf_plugins }}"
  when: item.versions is defined
  changed_when: no
  failed_when: no

- name: Set global asdf package versions
  shell: >-
    source {{ asdf_dir }}/asdf.sh &&
    asdf global {{ item.item.name }}
    {{ item.item.global | default(item.item.versions[0]) }}
  when: item.skipped is not defined and item.rc != 0
  with_items: "{{ asdf_plugins_versions.results }}"
