---
- name: Clone suckless tools repository
  git:
    repo: "{{ suckless_tools_git_src }}"
    dest: "{{ suckless_tools_git_dest }}"
    update: false
  become: true
  become_user: "{{ ansible_user_id }}"

- name: Build and install suckless tools
  make:
    target: install
    chdir: "{{ suckless_tools_git_dest }}/{{ item }}"
  loop:
    - dmenu
    - dwm
    - dwmblocks
    - slock
  become: true
