---
- name: Run the installation backend
  include_tasks: backend-makepkg.yml
  loop: "{{ makepkg_packages }}"
  loop_control:
    loop_var: package_name
  args:
    apply:
      become: true
      become_user: "{{ ansible_user_id }}"
